class Solution {
        public int maxStudents(char[][] seats) {
                int m = seats.length;
                        int n = seats[0].length;

                                int[] dp = new int[1 << n];

                                        for (int i = 0; i < m; i++) {
                                                    int[] next = new int[1 << n];

                                                                for (int mask = 0; mask < (1 << n); mask++) {
                                                                                boolean ok = true;
                                                                                                int count = 0;

                                                                                                                for (int j = 0; j < n; j++) {
                                                                                                                                    if ((mask & (1 << j)) != 0) {
                                                                                                                                                            if (seats[i][j] == '#' ||
                                                                                                                                                                                        (j > 0 && (mask & (1 << (j - 1))) != 0)) {
                                                                                                                                                                                                                    ok = false;
                                                                                                                                                                                                                                                break;
                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                count++;
                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                    if (!ok) continue;

                                                                                                                                                                                                                                                                                                                                                                    for (int prev = 0; prev < (1 << n); prev++) {
                                                                                                                                                                                                                                                                                                                                                                                        if ((prev & (mask << 1)) == 0 &&
                                                                                                                                                                                                                                                                                                                                                                                                                (prev & (mask >> 1)) == 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                        next[mask] = Math.max(next[mask], dp[prev] + count);
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    dp = next;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    int ans = 0;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for (int x : dp)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ans = Math.max(ans, x);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return ans;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };