class Solution {
        struct FactorCount {
                int c2 = 0, c3 = 0, c5 = 0, c7 = 0;
                    };

                        FactorCount getFactors(long long t) {
                                FactorCount fc;
                                        while (t % 2 == 0) { fc.c2++; t /= 2; }
                                                while (t % 3 == 0) { fc.c3++; t /= 3; }
                                                        while (t % 5 == 0) { fc.c5++; t /= 5; }
                                                                while (t % 7 == 0) { fc.c7++; t /= 7; }
                                                                        if (t > 1) return {-1, -1, -1, -1};
                                                                                return fc;
                                                                                    }

                                                                                        FactorCount getDigitFactors(int d) {
                                                                                                FactorCount fc;
                                                                                                        while (d > 1 && d % 2 == 0) { fc.c2++; d /= 2; }
                                                                                                                while (d > 1 && d % 3 == 0) { fc.c3++; d /= 3; }
                                                                                                                        while (d > 1 && d % 5 == 0) { fc.c5++; d /= 5; }
                                                                                                                                while (d > 1 && d % 7 == 0) { fc.c7++; d /= 7; }
                                                                                                                                        return fc;
                                                                                                                                            }

                                                                                                                                                int minDigitsNeeded(FactorCount req) {
                                                                                                                                                        req.c2 = max(0, req.c2);
                                                                                                                                                                req.c3 = max(0, req.c3);
                                                                                                                                                                        req.c5 = max(0, req.c5);
                                                                                                                                                                                req.c7 = max(0, req.c7);

                                                                                                                                                                                        int count = req.c5 + req.c7;
                                                                                                                                                                                                int c2 = req.c2;
                                                                                                                                                                                                        int c3 = req.c3;

                                                                                                                                                                                                                int count8 = c2 / 3;
                                                                                                                                                                                                                        c2 %= 3;
                                                                                                                                                                                                                                int count9 = c3 / 2;
                                                                                                                                                                                                                                        c3 %= 2;

                                                                                                                                                                                                                                                if (c2 == 2 && c3 == 1) {
                                                                                                                                                                                                                                                            count += 2;
                                                                                                                                                                                                                                                                        c2 = 0; c3 = 0;
                                                                                                                                                                                                                                                                                } else if (c2 == 1 && c3 == 1) {
                                                                                                                                                                                                                                                                                            count += 1;
                                                                                                                                                                                                                                                                                                        c2 = 0; c3 = 0;
                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                        count += count8 + count9;
                                                                                                                                                                                                                                                                                                                                if (c2 > 0) count += 1;
                                                                                                                                                                                                                                                                                                                                        if (c3 > 0) count += 1;

                                                                                                                                                                                                                                                                                                                                                return count;
                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                        FactorCount subtractFactors(FactorCount a, FactorCount b) {
                                                                                                                                                                                                                                                                                                                                                                return {a.c2 - b.c2, a.c3 - b.c3, a.c5 - b.c5, a.c7 - b.c7};
                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                    public:
                                                                                                                                                                                                                                                                                                                                                                        string smallestNumber(string num, long long t) {
                                                                                                                                                                                                                                                                                                                                                                                FactorCount targetFc = getFactors(t);
                                                                                                                                                                                                                                                                                                                                                                                        if (targetFc.c2 == -1) return "-1";

                                                                                                                                                                                                                                                                                                                                                                                                int n = num.length();

                                                                                                                                                                                                                                                                                                                                                                                                        int zeroIdx = -1;
                                                                                                                                                                                                                                                                                                                                                                                                                for (int i = 0; i < n; ++i) {
                                                                                                                                                                                                                                                                                                                                                                                                                            if (num[i] == '0') {
                                                                                                                                                                                                                                                                                                                                                                                                                                            zeroIdx = i;
                                                                                                                                                                                                                                                                                                                                                                                                                                                            break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        vector<FactorCount> prefFactors(n + 1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for (int i = 0; i < n; ++i) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (num[i] == '0') break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        FactorCount df = getDigitFactors(num[i] - '0');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    prefFactors[i + 1].c2 = prefFactors[i].c2 + df.c2;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                prefFactors[i + 1].c3 = prefFactors[i].c3 + df.c3;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            prefFactors[i + 1].c5 = prefFactors[i].c5 + df.c5;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        prefFactors[i + 1].c7 = prefFactors[i].c7 + df.c7;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        int maxPrefLen = (zeroIdx == -1) ? n : zeroIdx;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (zeroIdx == -1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            FactorCount req = subtractFactors(targetFc, prefFactors[n]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (minDigitsNeeded(req) == 0) return num;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for (int i = maxPrefLen; i >= 0; --i) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    int startDigit = (i < n) ? (num[i] - '0' + 1) : 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for (int d = startDigit; d <= 9; ++d) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                FactorCount curReq = subtractFactors(targetFc, prefFactors[i]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                FactorCount df = getDigitFactors(d);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                curReq = subtractFactors(curReq, df);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                int remLen = n - 1 - i;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (minDigitsNeeded(curReq) <= remLen) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    string ans = num.substr(0, i);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ans += to_string(d);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for (int j = 0; j < remLen; ++j) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for (int nextD = 1; nextD <= 9; ++nextD) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                FactorCount nextDf = getDigitFactors(nextD);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            FactorCount testReq = subtractFactors(curReq, nextDf);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (minDigitsNeeded(testReq) <= remLen - 1 - j) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ans += to_string(nextD);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        curReq = testReq;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return ans;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                int targetLen = n + 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        while (minDigitsNeeded(targetFc) > targetLen) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    targetLen++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    string ans = "";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            FactorCount curReq = targetFc;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for (int j = 0; j < targetLen; ++j) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for (int nextD = 1; nextD <= 9; ++nextD) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                FactorCount nextDf = getDigitFactors(nextD);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                FactorCount testReq = subtractFactors(curReq, nextDf);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (minDigitsNeeded(testReq) <= targetLen - 1 - j) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ans += to_string(nextD);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        curReq = testReq;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return ans;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };
